"""
Transaction models for HideX.

All transactions are designed to be:
- Previewable before execution
- Auditable after execution
- Explainable in terms of risk factors
"""

from datetime import datetime
from enum import Enum
from typing import Optional, Any
from pydantic import BaseModel, Field
from decimal import Decimal


class TransactionStatus(str, Enum):
    """Transaction lifecycle status."""
    PLANNED = "planned"  # Route planned, not yet simulated
    SIMULATED = "simulated"  # Simulation complete, awaiting confirmation
    PENDING_CONFIRMATION = "pending_confirmation"  # Awaiting user confirmation
    CONFIRMED = "confirmed"  # User confirmed, ready to execute
    EXECUTING = "executing"  # Currently being executed
    EXECUTED = "executed"  # Successfully executed
    FAILED = "failed"  # Execution failed
    CANCELLED = "cancelled"  # Cancelled by user


class TransactionStep(BaseModel):
    """
    A single step in a transaction plan.
    
    Each step represents one on-chain transaction.
    """
    id: str = Field(..., description="Unique step identifier")
    order: int = Field(..., ge=0, description="Execution order")
    
    # Source and destination
    from_address: str
    to_address: str
    chain: str = Field(default="ethereum")
    
    # Amount
    amount: str = Field(..., description="Amount in wei/smallest unit")
    amount_formatted: str = Field(..., description="Human-readable amount")
    
    # Timing
    delay_seconds: int = Field(
        default=0,
        ge=0,
        description="Delay before executing this step"
    )
    scheduled_at: Optional[datetime] = Field(default=None)
    
    # Gas/fee settings
    gas_limit: Optional[int] = Field(default=None)
    gas_price: Optional[str] = Field(default=None)
    max_fee_per_gas: Optional[str] = Field(default=None)
    max_priority_fee_per_gas: Optional[str] = Field(default=None)
    
    # Token transfer (if not native)
    token_address: Optional[str] = Field(default=None)
    token_symbol: Optional[str] = Field(default=None)
    
    # Execution results (filled after execution)
    tx_hash: Optional[str] = Field(default=None)
    block_number: Optional[int] = Field(default=None)
    status: TransactionStatus = Field(default=TransactionStatus.PLANNED)
    error_message: Optional[str] = Field(default=None)
    
    # Metadata
    description: Optional[str] = Field(default=None)
    metadata: dict[str, Any] = Field(default_factory=dict)


class TransactionPlan(BaseModel):
    """
    A complete transaction plan with multiple steps.
    
    Plans are generated by the Routing Planner and scored by
    the Risk Simulation Engine before execution.
    """
    id: str = Field(..., description="Unique plan identifier")
    name: Optional[str] = Field(default=None, description="User-defined name")
    description: Optional[str] = Field(default=None)
    
    # Plan configuration
    source_address: str = Field(..., description="Original source address")
    destination_address: str = Field(..., description="Final destination address")
    total_amount: str = Field(..., description="Total amount to transfer")
    total_amount_formatted: str
    chain: str = Field(default="ethereum")
    
    # Steps
    steps: list[TransactionStep] = Field(default_factory=list)
    
    # Status
    status: TransactionStatus = Field(default=TransactionStatus.PLANNED)
    
    # Risk assessment (filled by Risk Engine)
    risk_score: Optional[int] = Field(default=None, ge=0, le=100)
    risk_band: Optional[str] = Field(default=None)
    risk_factors: list[str] = Field(default_factory=list)
    risk_explanation: Optional[str] = Field(default=None)
    
    # Policy compliance
    policy_violations: list[str] = Field(default_factory=list)
    policy_warnings: list[str] = Field(default_factory=list)
    is_policy_compliant: bool = Field(default=True)
    
    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    simulated_at: Optional[datetime] = Field(default=None)
    confirmed_at: Optional[datetime] = Field(default=None)
    executed_at: Optional[datetime] = Field(default=None)
    
    # Dry-run mode
    is_dry_run: bool = Field(
        default=True,
        description="If true, only simulate, do not execute"
    )
    
    # Metadata
    metadata: dict[str, Any] = Field(default_factory=dict)


class Transaction(BaseModel):
    """
    Simplified transaction record for audit purposes.
    """
    id: str
    plan_id: str
    step_id: str
    tx_hash: str
    from_address: str
    to_address: str
    amount: str
    chain: str
    block_number: int
    timestamp: datetime
    gas_used: int
    gas_price: str
    status: str  # "success" or "failed"
    metadata: dict[str, Any] = Field(default_factory=dict)
